// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzusvsbkprwkjhhozaup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dXN2c2JrcHJ3a2poaG96YXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDg0MjIsImV4cCI6MjA2NDQ4NDQyMn0.3Xsdus_DjGsqWgrOg-mDhHaGL9EFnCyu3P5oLSSegX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);