name: Sleep Impressions ETL Pipeline

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main, etl-automation-setup]
    paths: ['enhanced-etl-processor.js', 'src/services/sleepImpressionsETL.ts']
  
jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Enhanced ETL Process
        run: node enhanced-etl-processor.js
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}

      - name: Upload ETL logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: etl-logs-${{ github.run_id }}
          path: etl-summary-*.json
          retention-days: 30

      - name: Notify on success
        if: success()
        run: |
          echo "✅ ETL process completed successfully"
          echo "📊 Check the uploaded logs for details"
          echo "🕐 Completed at: $(date)"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ ETL process failed"
          echo "📊 Check the uploaded logs for error details"
          echo "🕐 Failed at: $(date)"
